CREATE TABLE [dw].[date_dim]
(
[date_dim_key] [int] NOT NULL,
[calendar_date] [datetime2] (3) NULL,
[cal_day_in_week] [nvarchar] (15) COLLATE Latin1_General_CI_AS NULL,
[cal_day_in_week_no] [int] NULL,
[cal_day_in_month] [int] NULL,
[cal_day_in_year] [int] NULL,
[cal_week_in_year] [int] NULL,
[cal_month_no] [int] NULL,
[cal_month] [int] NULL,
[cal_month_name] [nvarchar] (15) COLLATE Latin1_General_CI_AS NULL,
[cal_quarter_no] [int] NULL,
[cal_quarter] [int] NULL,
[cal_year] [int] NULL,
[financial_date] [datetime2] (3) NULL,
[fin_day_in_week] [nvarchar] (15) COLLATE Latin1_General_CI_AS NULL,
[fin_day_in_week_no] [int] NULL,
[fin_day_in_month] [int] NULL,
[fin_day_in_year] [int] NULL,
[fin_week_in_year] [int] NULL,
[fin_month_no] [int] NULL,
[fin_month] [int] NULL,
[fin_month_name] [nvarchar] (15) COLLATE Latin1_General_CI_AS NULL,
[fin_period] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[fin_quarter_no] [int] NULL,
[fin_quarter] [int] NULL,
[fin_year] [int] NULL,
[week_day_flag] [nvarchar] (15) COLLATE Latin1_General_CI_AS NULL,
[week_end_flag] [nvarchar] (15) COLLATE Latin1_General_CI_AS NULL,
[holiday_flag] [nvarchar] (15) COLLATE Latin1_General_CI_AS NULL,
[holiday_desc] [nvarchar] (64) COLLATE Latin1_General_CI_AS NULL,
[trading_day_flag] [nvarchar] (15) COLLATE Latin1_General_CI_AS NULL,
[trading_days_in_mth] [int] NULL,
[trading_days_so_far] [int] NULL,
[dss_update_time] [datetime2] (3) NULL,
[semester] [tinyint] NOT NULL,
[current_semester_indicator] [tinyint] NOT NULL,
[today_indicator] [tinyint] NOT NULL,
[yesterday_indicator] [tinyint] NOT NULL,
[tomorrow_indicator] [tinyint] NOT NULL,
[current_week_indicator] [tinyint] NOT NULL,
[last_week_indicator] [tinyint] NOT NULL,
[next_week_indicator] [tinyint] NOT NULL,
[current_month_indicator] [tinyint] NOT NULL,
[last_month_indicator] [tinyint] NOT NULL,
[next_month_indicator] [tinyint] NOT NULL,
[current_year_indicator] [tinyint] NOT NULL,
[last_year_indicator] [tinyint] NOT NULL,
[next_year_indicator] [tinyint] NOT NULL,
[last_three_years_indicator] [tinyint] NOT NULL
) ON [PRIMARY]
GO
