CREATE TABLE [dw].[programme_dim_2]
(
[programme_key] [bigint] NOT NULL,
[previous_programme_key] [bigint] NOT NULL,
[programme_id] [bigint] NOT NULL,
[repository_id] [bigint] NOT NULL,
[official_programme_code] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[programme_code] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[abbreviated_title] [nvarchar] (100) COLLATE Latin1_General_CI_AS NOT NULL,
[long_description] [nvarchar] (2000) COLLATE Latin1_General_CI_AS NOT NULL,
[programme_type] [nvarchar] (240) COLLATE Latin1_General_CI_AS NOT NULL,
[intake_extension_code] [nvarchar] (15) COLLATE Latin1_General_CI_AS NOT NULL,
[programme_intake_code] [nvarchar] (30) COLLATE Latin1_General_CI_AS NOT NULL,
[description] [nvarchar] (100) COLLATE Latin1_General_CI_AS NOT NULL,
[owning_cluster] [nvarchar] (500) COLLATE Latin1_General_CI_AS NOT NULL,
[delivery_cluster] [nvarchar] (500) COLLATE Latin1_General_CI_AS NOT NULL,
[national_credits] [decimal] (5, 2) NOT NULL,
[local_credits] [decimal] (5, 2) NOT NULL,
[level] [int] NOT NULL,
[efts] [decimal] (6, 5) NOT NULL,
[owning_start_date] [datetime2] (3) NOT NULL,
[owning_end_date] [datetime2] (3) NOT NULL,
[version_number] [nvarchar] (15) COLLATE Latin1_General_CI_AS NOT NULL,
[duration_value] [decimal] (5, 2) NOT NULL,
[duration_measure] [nvarchar] (15) COLLATE Latin1_General_CI_AS NOT NULL,
[status] [nvarchar] (240) COLLATE Latin1_General_CI_AS NOT NULL,
[requires_application_indicator] [tinyint] NOT NULL,
[default_qualification_code] [nvarchar] (15) COLLATE Latin1_General_CI_AS NOT NULL,
[nzsced] [nvarchar] (15) COLLATE Latin1_General_CI_AS NOT NULL,
[nzsced_title] [nvarchar] (240) COLLATE Latin1_General_CI_AS NOT NULL,
[delivery_source_of_funding_code] [nvarchar] (15) COLLATE Latin1_General_CI_AS NOT NULL,
[delivery_source_of_funding_name] [nvarchar] (240) COLLATE Latin1_General_CI_AS NOT NULL,
[delivery_status] [nvarchar] (40) COLLATE Latin1_General_CI_AS NOT NULL,
[minimum_places] [int] NOT NULL,
[maximum_places] [int] NOT NULL,
[target_enrolments] [int] NOT NULL,
[delivery_version_number] [int] NOT NULL,
[delivery_efts] [decimal] (6, 5) NOT NULL,
[delivery_start_date] [datetime2] (3) NOT NULL,
[delivery_end_date] [datetime2] (3) NOT NULL,
[delivery_cost_center_code] [nvarchar] (30) COLLATE Latin1_General_CI_AS NOT NULL,
[owning_cost_center_code] [nvarchar] (30) COLLATE Latin1_General_CI_AS NOT NULL,
[delivery_cost_center_name] [nvarchar] (100) COLLATE Latin1_General_CI_AS NOT NULL,
[delivery_department_code] [nvarchar] (30) COLLATE Latin1_General_CI_AS NOT NULL,
[owning_department_code] [nvarchar] (30) COLLATE Latin1_General_CI_AS NOT NULL,
[delivery_department_name] [nvarchar] (100) COLLATE Latin1_General_CI_AS NOT NULL,
[owning_department_name] [nvarchar] (100) COLLATE Latin1_General_CI_AS NOT NULL,
[delivery_division_code] [nvarchar] (30) COLLATE Latin1_General_CI_AS NOT NULL,
[delivery_division_name] [nvarchar] (100) COLLATE Latin1_General_CI_AS NOT NULL,
[owning_division_code] [nvarchar] (30) COLLATE Latin1_General_CI_AS NOT NULL,
[owning_division_name] [nvarchar] (100) COLLATE Latin1_General_CI_AS NOT NULL,
[delivery_location_code] [nvarchar] (15) COLLATE Latin1_General_CI_AS NOT NULL,
[delivery_location] [nvarchar] (40) COLLATE Latin1_General_CI_AS NOT NULL,
[can_enquire_indicator] [tinyint] NOT NULL,
[can_apply_indicator] [tinyint] NOT NULL,
[can_enrol_indicator] [tinyint] NOT NULL,
[can_wait_list_indicator] [tinyint] NOT NULL,
[web_enquire_indicator] [tinyint] NOT NULL,
[web_apply_indicator] [tinyint] NOT NULL,
[web_enrol_indicator] [tinyint] NOT NULL,
[data_source] [nvarchar] (30) COLLATE Latin1_General_CI_AS NOT NULL,
[dw_current_indicator] [tinyint] NOT NULL,
[dw_status] [nvarchar] (15) COLLATE Latin1_General_CI_AS NOT NULL,
[dw_effective_date] [datetime2] (3) NOT NULL,
[dw_expiration_date] [datetime2] (3) NOT NULL,
[dw_created_date] [datetime2] (3) NOT NULL,
[dw_updated_date] [datetime2] (3) NOT NULL
) ON [PRIMARY]
GO
