CREATE TABLE [dw].[programme_dim]
(
[programme_key] [bigint] NOT NULL,
[programme_id] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[official_programme_code] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[programme_code] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[abbreviated_title] [nvarchar] (100) COLLATE Latin1_General_CI_AS NOT NULL,
[long_description] [nvarchar] (2000) COLLATE Latin1_General_CI_AS NOT NULL,
[programme_type] [nvarchar] (240) COLLATE Latin1_General_CI_AS NOT NULL,
[national_credits] [numeric] (5, 2) NOT NULL,
[local_credits] [numeric] (5, 2) NOT NULL,
[level] [int] NOT NULL,
[efts] [numeric] (6, 5) NOT NULL,
[start_date] [datetime2] (3) NOT NULL,
[end_date] [datetime2] (3) NOT NULL,
[version_number] [nvarchar] (15) COLLATE Latin1_General_CI_AS NOT NULL,
[duration_value] [numeric] (5, 2) NOT NULL,
[duration_measure] [nvarchar] (15) COLLATE Latin1_General_CI_AS NOT NULL,
[status] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[requires_application_indicator] [tinyint] NOT NULL,
[default_qualification_code] [nvarchar] (15) COLLATE Latin1_General_CI_AS NOT NULL,
[nzsced] [nvarchar] (15) COLLATE Latin1_General_CI_AS NOT NULL,
[nzsced_title] [nvarchar] (240) COLLATE Latin1_General_CI_AS NOT NULL,
[owning_cost_center_code] [nvarchar] (30) COLLATE Latin1_General_CI_AS NOT NULL,
[owning_department_code] [nvarchar] (30) COLLATE Latin1_General_CI_AS NOT NULL,
[owning_division_code] [nvarchar] (30) COLLATE Latin1_General_CI_AS NOT NULL,
[owning_department_name] [nvarchar] (100) COLLATE Latin1_General_CI_AS NOT NULL,
[owning_division_name] [nvarchar] (100) COLLATE Latin1_General_CI_AS NOT NULL,
[data_source] [nvarchar] (30) COLLATE Latin1_General_CI_AS NOT NULL,
[cluster] [nvarchar] (500) COLLATE Latin1_General_CI_AS NOT NULL,
[dw_current_indicator] [tinyint] NOT NULL,
[dw_status] [nvarchar] (15) COLLATE Latin1_General_CI_AS NOT NULL,
[dw_effective_date] [datetime2] (3) NOT NULL,
[dw_expiration_date] [datetime2] (3) NOT NULL,
[dw_created_date] [datetime2] (3) NOT NULL,
[dw_updated_date] [datetime2] (3) NOT NULL
) ON [PRIMARY]
GO
